BEGIN;

ALTER TABLE login_logs ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE login_logs ADD COLUMN IF NOT EXISTS area TEXT;
ALTER TABLE login_logs ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE login_logs ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE login_logs ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

COMMIT;
