const fs = require('fs');
const path = require('path');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const fontkit = require('@pdf-lib/fontkit');

const UNICODE_FONT_PATH = path.join(
  __dirname,
  '../assets/fonts/NotoSansArabic-Regular.ttf'
);
const LOGO_PATH = path.join(__dirname, '../assets/logo.png');

let unicodeFontBytes = null;
let logoPngBytes = null;
try {
  unicodeFontBytes = fs.readFileSync(UNICODE_FONT_PATH);
} catch (err) {
  console.warn('attendance export PDF font missing:', err.message || err);
}
try {
  logoPngBytes = fs.readFileSync(LOGO_PATH);
} catch (err) {
  console.warn('attendance export PDF logo missing:', err.message || err);
}

const ATTENDANCE_SUMMARY_COLUMNS = [
  { key: 'employee_id', label: 'Employee ID', width: 80 },
  { key: 'name', label: 'Name', width: 130 },
  { key: 'department', label: 'Team', width: 95 },
  { key: 'branch', label: 'Branch', width: 90 },
  { key: 'shift', label: 'Shift', width: 75 },
  { key: 'total_days', label: 'Total Days', width: 60 },
  { key: 'working_days', label: 'Working Days', width: 70 },
  { key: 'present_days', label: 'Present / On Time', width: 85 },
  { key: 'late_days', label: 'Late', width: 55 },
  { key: 'absent_days', label: 'Absent', width: 60 },
  { key: 'leave_days', label: 'Leave', width: 55 },
  { key: 'holiday_days', label: 'Holidays', width: 60 },
  { key: 'attendance_rate', label: 'Attendance %', width: 75 },
];

function xmlEscape(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function filenamePart(value, fallback) {
  const cleaned = String(value || '')
    .replace(/[<>:"/\\|?*\u0000-\u001f]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned || fallback;
}

function buildAttendanceBaseName(filters = {}, monthKey = '') {
  const month = filenamePart(monthKey || 'Month', 'Month');
  const team = filters.team
    ? filenamePart(filters.team, 'All Teams')
    : 'All Teams';
  const branch = filters.branch
    ? filenamePart(filters.branch, 'All Branches')
    : 'All Branches';
  const shift = filters.shift
    ? filenamePart(filters.shift, 'All Shifts')
    : '';

  return ['TL Attendance', month, team, branch, shift]
    .filter(Boolean)
    .join(' ')
    .trim();
}

function excelSheetPasswordHash(password) {
  const text = String(password || '');
  let verifier = 0;
  for (let i = text.length - 1; i >= 0; i -= 1) {
    verifier = ((verifier >> 14) & 0x01) | ((verifier << 1) & 0x7fff);
    verifier ^= text.charCodeAt(i) & 0xff;
  }
  verifier = ((verifier >> 14) & 0x01) | ((verifier << 1) & 0x7fff);
  verifier ^= text.length;
  verifier ^= 0xce4b;
  return verifier.toString(16).toUpperCase().padStart(4, '0');
}

function displayAttendanceRows(records) {
  return (records || []).map((row) => ({
    id: row.id,
    employee_id: row.employee_id || '—',
    name: row.name || '—',
    department: row.department || '—',
    branch: row.branch || '—',
    shift: row.shift || '—',
    total_days: Number(row.total_days ?? 0),
    working_days: Number(row.working_days ?? 0),
    present_days: Number(row.present_days ?? 0),
    late_days: Number(row.late_days ?? 0),
    absent_days: Number(row.absent_days ?? 0),
    leave_days: Number(row.leave_days ?? 0),
    holiday_days: Number(row.holiday_days ?? 0),
    attendance_rate: `${Number(row.attendance_rate ?? 0)}%`,
    daily_codes: row.daily_codes || {},
  }));
}

function buildAttendanceExcelXml(records, daysInMonth = [], meta = {}) {
  const rows = displayAttendanceRows(records);
  const sheetPassword = excelSheetPasswordHash(
    process.env.EXPORT_SHEET_PASSWORD || 'TL-attendance-A1'
  );

  const generatedBy = String(meta.generatedBy || '').trim() || 'Unknown';
  const generatedLabel = xmlEscape(`Report generated by ${generatedBy}`);
  const monthTitle = xmlEscape(meta.month || meta.monthKey || 'Monthly Attendance');
  const subtitle = xmlEscape(
    [
      meta.title || 'Textured Lab Attendance Export',
      `Month: ${meta.month || meta.monthKey}`,
      meta.filters || '',
      `${rows.length} ${rows.length === 1 ? 'employee' : 'employees'}`,
    ]
      .filter(Boolean)
      .join(' | ')
  );

  // Sheet 1: Summary Columns
  const summaryColDefs = ATTENDANCE_SUMMARY_COLUMNS.map(
    (col) => `<Column ss:Width="${col.width}"/>`
  ).join('');

  const summaryHeaderCells = ATTENDANCE_SUMMARY_COLUMNS.map(
    (col) => `<Cell ss:StyleID="Header"><Data ss:Type="String">${xmlEscape(col.label)}</Data></Cell>`
  ).join('');

  const summaryBodyRows = rows
    .map((row, index) => {
      const style = index % 2 === 1 ? ' ss:StyleID="Stripe"' : '';
      const cells = ATTENDANCE_SUMMARY_COLUMNS.map((col) => {
        const val = row[col.key] ?? '';
        const isNumeric = typeof val === 'number';
        return `<Cell${style}><Data ss:Type="${isNumeric ? 'Number' : 'String'}">${xmlEscape(val)}</Data></Cell>`;
      }).join('');
      return `<Row>${cells}</Row>`;
    })
    .join('');

  // Sheet 2: Daily Muster Roll Grid
  const dailyColDefs = [
    '<Column ss:Width="75"/>',  // Emp ID
    '<Column ss:Width="120"/>', // Name
    '<Column ss:Width="85"/>',  // Team
    '<Column ss:Width="80"/>',  // Branch
    ...daysInMonth.map(() => '<Column ss:Width="36"/>'),
    '<Column ss:Width="55"/>',  // Total Present
    '<Column ss:Width="50"/>',  // Total Late
    '<Column ss:Width="50"/>',  // Total Absent
    '<Column ss:Width="50"/>',  // Total Leave
    '<Column ss:Width="55"/>',  // Rate %
  ].join('');

  const dailyHeaderCells = [
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Emp ID</Data></Cell>',
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Name</Data></Cell>',
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Team</Data></Cell>',
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Branch</Data></Cell>',
    ...daysInMonth.map((d) => {
      const label = `${String(d.day).padStart(2, '0')} ${d.weekdayShort || ''}`;
      return `<Cell ss:StyleID="${d.isSunday ? 'HolidayHeader' : 'Header'}"><Data ss:Type="String">${xmlEscape(label)}</Data></Cell>`;
    }),
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Present</Data></Cell>',
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Late</Data></Cell>',
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Absent</Data></Cell>',
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Leave</Data></Cell>',
    '<Cell ss:StyleID="Header"><Data ss:Type="String">Rate %</Data></Cell>',
  ].join('');

  const dailyTotalColsCount = 4 + daysInMonth.length + 5;

  const dailyBodyRows = rows
    .map((row) => {
      const baseCells = [
        `<Cell ss:StyleID="TextCell"><Data ss:Type="String">${xmlEscape(row.employee_id)}</Data></Cell>`,
        `<Cell ss:StyleID="TextCellBold"><Data ss:Type="String">${xmlEscape(row.name)}</Data></Cell>`,
        `<Cell ss:StyleID="TextCell"><Data ss:Type="String">${xmlEscape(row.department)}</Data></Cell>`,
        `<Cell ss:StyleID="TextCell"><Data ss:Type="String">${xmlEscape(row.branch)}</Data></Cell>`,
      ];

      const dayCells = daysInMonth.map((d) => {
        const code = row.daily_codes?.[d.dateKey] || (d.isSunday ? 'H' : '-');
        let styleId = 'NormalCell';
        if (code === 'P') styleId = 'PresentCell';
        else if (code === 'L') styleId = 'LateCell';
        else if (code === 'A') styleId = 'AbsentCell';
        else if (code === 'Lv') styleId = 'LeaveCell';
        else if (code === 'H') styleId = 'HolidayCell';
        return `<Cell ss:StyleID="${styleId}"><Data ss:Type="String">${xmlEscape(code)}</Data></Cell>`;
      });

      const statCells = [
        `<Cell ss:StyleID="StatCell"><Data ss:Type="Number">${row.present_days}</Data></Cell>`,
        `<Cell ss:StyleID="StatCell"><Data ss:Type="Number">${row.late_days}</Data></Cell>`,
        `<Cell ss:StyleID="StatCell"><Data ss:Type="Number">${row.absent_days}</Data></Cell>`,
        `<Cell ss:StyleID="StatCell"><Data ss:Type="Number">${row.leave_days}</Data></Cell>`,
        `<Cell ss:StyleID="StatCellBold"><Data ss:Type="String">${xmlEscape(row.attendance_rate)}</Data></Cell>`,
      ];

      return `<Row>${baseCells.join('')}${dayCells.join('')}${statCells.join('')}</Row>`;
    })
    .join('');

  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="Header">
   <Font ss:Bold="1" ss:Color="#FFFFFF"/>
   <Interior ss:Color="#1B2A4A" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="HolidayHeader">
   <Font ss:Bold="1" ss:Color="#FFFFFF"/>
   <Interior ss:Color="#475569" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="Meta">
   <Font ss:Italic="1" ss:Color="#475569" ss:Size="10"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="Legend">
   <Font ss:Bold="1" ss:Color="#1E293B" ss:Size="9"/>
   <Interior ss:Color="#F1F5F9" ss:Pattern="Solid"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="Stripe">
   <Interior ss:Color="#F8FAFC" ss:Pattern="Solid"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="GeneratedBy">
   <Font ss:Bold="1" ss:Color="#1B2A4A" ss:Size="11"/>
   <Protection ss:Protected="1"/>
  </Style>
  <Style ss:ID="PresentCell">
   <Font ss:Bold="1" ss:Color="#15803D"/>
   <Interior ss:Color="#DCFCE7" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="LateCell">
   <Font ss:Bold="1" ss:Color="#B45309"/>
   <Interior ss:Color="#FEF3C7" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="AbsentCell">
   <Font ss:Bold="1" ss:Color="#B91C1C"/>
   <Interior ss:Color="#FEE2E2" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="LeaveCell">
   <Font ss:Bold="1" ss:Color="#6D28D9"/>
   <Interior ss:Color="#EDE9FE" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="HolidayCell">
   <Font ss:Color="#64748B"/>
   <Interior ss:Color="#F1F5F9" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="NormalCell">
   <Font ss:Color="#94A3B8"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="TextCell">
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="TextCellBold">
   <Font ss:Bold="1" ss:Color="#0F172A"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="StatCell">
   <Alignment ss:Horizontal="Right" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
  <Style ss:ID="StatCellBold">
   <Font ss:Bold="1" ss:Color="#0F172A"/>
   <Alignment ss:Horizontal="Right" ss:Vertical="Center"/>
   <Protection ss:Protected="0"/>
  </Style>
 </Styles>

 <!-- Worksheet 1: Summary -->
 <Worksheet ss:Name="Attendance Summary" ss:Protected="1">
  <Table>
   ${summaryColDefs}
   <Row>
    <Cell ss:StyleID="GeneratedBy"><Data ss:Type="String">TEXTURED LAB · ${monthTitle}</Data></Cell>
   </Row>
   <Row>
    <Cell ss:MergeAcross="${ATTENDANCE_SUMMARY_COLUMNS.length - 1}" ss:StyleID="Meta"><Data ss:Type="String">${subtitle} · ${generatedLabel}</Data></Cell>
   </Row>
   <Row><Cell ss:StyleID="Default"/></Row>
   <Row>${summaryHeaderCells}</Row>
   ${summaryBodyRows}
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <FreezePanes/><FrozenNoSplit/><SplitHorizontal>4</SplitHorizontal><TopRowBottomPane>4</TopRowBottomPane>
   <EnableSelection>UnlockedCells</EnableSelection>
   <ProtectContents>True</ProtectContents>
   <ProtectObjects>True</ProtectObjects>
   <ProtectScenarios>True</ProtectScenarios>
   <Password>${sheetPassword}</Password>
  </WorksheetOptions>
 </Worksheet>

 <!-- Worksheet 2: Daily Register (Muster Roll) -->
 <Worksheet ss:Name="Daily Register (Muster Roll)" ss:Protected="1">
  <Table>
   ${dailyColDefs}
   <Row>
    <Cell ss:StyleID="GeneratedBy"><Data ss:Type="String">DAILY ATTENDANCE REGISTER · ${monthTitle}</Data></Cell>
   </Row>
   <Row>
    <Cell ss:MergeAcross="${dailyTotalColsCount - 1}" ss:StyleID="Meta"><Data ss:Type="String">${subtitle} · ${generatedLabel}</Data></Cell>
   </Row>
   <Row>
    <Cell ss:MergeAcross="${dailyTotalColsCount - 1}" ss:StyleID="Legend"><Data ss:Type="String">LEGEND: P = Present / On Time | L = Late | A = Absent | Lv = Leave | H = Sunday / Holiday | - = Pending / Future / Not Joined</Data></Cell>
   </Row>
   <Row>${dailyHeaderCells}</Row>
   ${dailyBodyRows}
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <FreezePanes/><FrozenNoSplit/>
   <SplitHorizontal>4</SplitHorizontal><TopRowBottomPane>4</TopRowBottomPane>
   <SplitVertical>2</SplitVertical><LeftColumnRightPane>2</LeftColumnRightPane>
   <EnableSelection>UnlockedCells</EnableSelection>
   <ProtectContents>True</ProtectContents>
   <ProtectObjects>True</ProtectObjects>
   <ProtectScenarios>True</ProtectScenarios>
   <Password>${sheetPassword}</Password>
  </WorksheetOptions>
 </Worksheet>
</Workbook>`;
}

function textWidth(font, text, size) {
  try {
    return font.widthOfTextAtSize(String(text || ''), size);
  } catch {
    return String(text || '').length * size * 0.5;
  }
}

function safeDrawText(page, text, opts) {
  try {
    page.drawText(String(text || ''), opts);
  } catch {
    const fallback = String(text || '').replace(/[^\x09\x0a\x0d\x20-\x7e]/g, '?');
    page.drawText(fallback, opts);
  }
}

async function embedExportFonts(pdf) {
  if (unicodeFontBytes) {
    try {
      pdf.registerFontkit(fontkit);
      const embedded = await pdf.embedFont(unicodeFontBytes, { subset: true });
      return { font: embedded, bold: embedded };
    } catch {
      /* fallback */
    }
  }
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  return { font, bold };
}

async function buildAttendancePdf(records, daysInMonth = [], meta = {}) {
  const rows = displayAttendanceRows(records);
  const pdf = await PDFDocument.create();
  const { font, bold } = await embedExportFonts(pdf);

  let logoImage = null;
  if (logoPngBytes) {
    try {
      logoImage = await pdf.embedPng(logoPngBytes);
    } catch (err) {
      console.warn('attendance export PDF logo embed failed:', err.message || err);
    }
  }

  // A4 Landscape
  const pageWidth = 842;
  const pageHeight = 595;
  const margin = 28;
  const innerWidth = pageWidth - margin * 2; // 786 pt

  const ink = rgb(0.09, 0.12, 0.18);
  const muted = rgb(0.38, 0.42, 0.5);
  const band = rgb(0.1, 0.16, 0.28);
  const section = rgb(0.42, 0.47, 0.55);
  const rowStripe = rgb(0.965, 0.975, 0.985);
  const rule = rgb(0.85, 0.88, 0.92);

  // Table columns without Type (fits innerWidth = 786)
  const cols = [
    { key: 'employee_id', label: 'Emp ID', width: 68, align: 'left' },
    { key: 'name', label: 'Employee Name', width: 145, align: 'left' },
    { key: 'department', label: 'Team', width: 95, align: 'left' },
    { key: 'branch', label: 'Branch', width: 90, align: 'left' },
    { key: 'shift', label: 'Shift', width: 70, align: 'left' },
    { key: 'working_days', label: 'Work Days', width: 55, align: 'right' },
    { key: 'present_days', label: 'Present', width: 55, align: 'right' },
    { key: 'late_days', label: 'Late', width: 48, align: 'right' },
    { key: 'absent_days', label: 'Absent', width: 48, align: 'right' },
    { key: 'leave_days', label: 'Leave', width: 48, align: 'right' },
    { key: 'attendance_rate', label: 'Rate %', width: 58, align: 'right' },
  ];

  let page = null;
  let y = 0;
  let pageNo = 0;

  function drawRight(text, atY, size, usedFont, color) {
    const width = textWidth(usedFont, text, size);
    safeDrawText(page, text, {
      x: pageWidth - margin - width,
      y: atY,
      size,
      font: usedFont,
      color,
    });
  }

  function drawWatermark(target) {
    if (!logoImage) return;
    const maxSide = Math.min(pageWidth, pageHeight) * 0.55;
    const scale = Math.min(maxSide / logoImage.width, maxSide / logoImage.height);
    const width = logoImage.width * scale;
    const height = logoImage.height * scale;
    target.drawImage(logoImage, {
      x: (pageWidth - width) / 2,
      y: (pageHeight - height) / 2,
      width,
      height,
      opacity: 0.12,
    });
  }

  function addPage() {
    page = pdf.addPage([pageWidth, pageHeight]);
    pageNo += 1;
    y = pageHeight - margin;

    // Brand header
    safeDrawText(page, 'TEXTURED LAB', {
      x: margin,
      y,
      size: 9,
      font: bold,
      color: section,
    });
    drawRight('Confidential monthly attendance record', y, 8, font, section);
    y -= 13;

    const generatedBy = String(meta.generatedBy || '').trim();
    if (generatedBy) {
      drawRight(`Report generated by ${generatedBy}`, y, 8, font, section);
    }

    // Title
    safeDrawText(page, meta.title || 'Monthly Attendance Report', {
      x: margin,
      y,
      size: 15,
      font: bold,
      color: ink,
    });
    y -= 16;

    // Subtitle
    const monthLabel = meta.month || meta.monthKey || '';
    safeDrawText(
      page,
      `Month: ${monthLabel}  |  ${meta.filters || 'All Employees'}  |  ${rows.length} ${rows.length === 1 ? 'employee' : 'employees'}  |  ${meta.generatedAt || ''}`,
      { x: margin, y, size: 8.5, font, color: muted }
    );
    y -= 10;

    // Divider line
    page.drawLine({
      start: { x: margin, y: y + 3 },
      end: { x: pageWidth - margin, y: y + 3 },
      thickness: 1.2,
      color: band,
    });
    y -= 10;

    // Table Header
    drawTableHeader();
  }

  function drawTableHeader() {
    const headerH = 18;
    page.drawRectangle({
      x: margin,
      y: y - headerH,
      width: innerWidth,
      height: headerH,
      color: band,
    });

    let currentX = margin + 6;
    cols.forEach((col) => {
      let drawX = currentX;
      if (col.align === 'right') {
        const tw = textWidth(bold, col.label, 7.5);
        drawX = currentX + col.width - tw - 4;
      } else if (col.align === 'center') {
        const tw = textWidth(bold, col.label, 7.5);
        drawX = currentX + (col.width - tw) / 2;
      }
      safeDrawText(page, col.label, {
        x: drawX,
        y: y - 12,
        size: 7.5,
        font: bold,
        color: rgb(0.97, 0.98, 0.99),
      });
      currentX += col.width;
    });

    y -= (headerH + 2);
  }

  addPage();

  if (!rows.length) {
    safeDrawText(page, 'No employees matched the selected filters.', {
      x: margin,
      y: y - 20,
      size: 10,
      font,
      color: muted,
    });
    return Buffer.from(await pdf.save());
  }

  const rowHeight = 17;
  for (let rIdx = 0; rIdx < rows.length; rIdx += 1) {
    const row = rows[rIdx];

    // Check if new page needed
    if (y - rowHeight < margin + 25) {
      addPage();
    }

    // Alternating zebra stripe
    if (rIdx % 2 === 1) {
      page.drawRectangle({
        x: margin,
        y: y - rowHeight,
        width: innerWidth,
        height: rowHeight,
        color: rowStripe,
      });
    }

    // Bottom row border line
    page.drawLine({
      start: { x: margin, y: y - rowHeight },
      end: { x: pageWidth - margin, y: y - rowHeight },
      thickness: 0.4,
      color: rule,
    });

    let currentX = margin + 6;
    cols.forEach((col) => {
      let val = String(row[col.key] ?? '—');
      const maxW = col.width - 6;
      while (textWidth(font, val, 7.5) > maxW && val.length > 3) {
        val = val.slice(0, -2) + '…';
      }

      let drawX = currentX;
      if (col.align === 'right') {
        const tw = textWidth(font, val, 7.5);
        drawX = currentX + col.width - tw - 4;
      } else if (col.align === 'center') {
        const tw = textWidth(font, val, 7.5);
        drawX = currentX + (col.width - tw) / 2;
      }

      const isRate = col.key === 'attendance_rate';
      safeDrawText(page, val, {
        x: drawX,
        y: y - 11.5,
        size: 7.5,
        font: isRate || col.key === 'employee_id' ? bold : font,
        color: ink,
      });

      currentX += col.width;
    });

    y -= rowHeight;
  }

  // Footer and watermark on all pages
  const allPages = pdf.getPages();
  allPages.forEach((p, idx) => {
    drawWatermark(p);
    safeDrawText(p, `Page ${idx + 1} of ${allPages.length}`, {
      x: pageWidth / 2 - 25,
      y: 12,
      size: 7.5,
      font,
      color: muted,
    });
    safeDrawText(p, 'Confidential · Textured Lab HR & Attendance Management', {
      x: margin,
      y: 12,
      size: 7,
      font,
      color: muted,
    });
  });

  return Buffer.from(await pdf.save());
}

module.exports = {
  ATTENDANCE_SUMMARY_COLUMNS,
  buildAttendanceExcelXml,
  buildAttendancePdf,
  buildAttendanceBaseName,
  displayAttendanceRows,
};
